version: "3.4"

services:
  scylladb:
    image: scylladb/scylla:4.1.0
    command: --smp 1 --memory 1G
    ports:
      - 9042:9042
    volumes:
      - ./docker-data/scylladb:/var/lib/scylla
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep UN"]
      interval: 30s
      timeout: 10s
      retries: 3

  rabbitmq:
    image: rabbitmq:3
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 3

  node:
    build:
      context: .
      dockerfile: docker/twake-node/Dockerfile
    environment:
      - NODE_ENV=production
      - PUBSUB_URLS=amqp://guest:guest@rabbitmq:5672
      - SEARCH_ES_ENDPOINT=http://elasticsearch:9200
    volumes:
      - ./default-configuration/backend-node/production.json:/usr/src/app/config/production.json
      - ./docker-data/documents/:/storage/
    depends_on:
      scylladb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  php:
    build:
      context: .
      dockerfile: docker/twake-php/Dockerfile
    environment:
      - DEV=production
    volumes:
      - ./default-configuration/backend/Parameters.php:/configuration/Parameters.php
      - ./connectors/:/twake-core/src/BuiltInConnectors/Connectors
      - ./docker-data/drive/:/twake-core/drive/
      - ./docker-data/fpm/:/etc/docker-data/fpm/
      - ./docker-data/drive-preview/:/twake-core/web/medias/
      - ./docker-data/uploads/:/twake-core/web/upload/
    depends_on:
      scylladb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker-data/es:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cat/nodes?v\\&pretty || exit 1" ]
    ports:
      - 9200:9200

  nginx:
    build:
      context: .
      dockerfile: docker/twake-nginx-php-only/Dockerfile
    environment:
      - DEV=production
      - SSL_CERTS=none
    ports:
      - 7777:80
      - 4433:443
    depends_on:
      - php
      - node
    volumes:
      - ./docker-data/logs/nginx/:/var/log/nginx
      - ./docker-data/letsencrypt/:/etc/letsencrypt/
      - ./docker-data/drive-preview/:/twake-core/web/medias/
      - ./docker-data/uploads/:/twake-core/web/upload/
      - ./docker-data/ssl:/etc/nginx/ssl
